### ISSUE TITLE
2018-09-24T22:26:44Z: Daily Todo

### ISSUE THREAD

**Issue by abhiyerra** [startupsonoma/community#10]
# Daily

## Sales / Pipedrive

 - [ ] Contacted / Create Deal
 - [ ] Deals / Lead In
    - https://startupsonomacounty.pipedrive.com/pipeline/1/user/everyone
    - Create Activities (What the Next Steps Are)
    - Find Contact Information / Research Contact Information
 - [ ] People/ Ensure Emails Exist
    - All these People Need to Have Emails associated with them:
        - https://startupsonomacounty.pipedrive.com/persons/list
    - Note: Ask Dana, Tyler or Abhi for information

## Trello

https://trello.com/b/JzOSb2w9/tasks

 - [ ] Organize
 - [ ] Admin Tasks

# Building

 - [ ] Cleaning

# Finance

 - [ ] Receipts
