### ISSUE TITLE
2018-09-26T21:22:48Z: Quarterly Todo

### ISSUE THREAD

**Issue by abhiyerra** [startupsonoma/community#13]
# Quarterly

## Value Delivery

 - [ ] Operating Agreement
    https://docs.google.com/document/d/1WEiRULiKdU4Mwnyyho0bXkKDiu-YLLeaqLyHcYn7OxM/edit
 - [ ] Strategy

### Taxes

[IRS Payment](https://www.irs.gov/payments/direct-pay)

    Payment Period: Due Date
    January 1 – March 31: April 15
    April 1 – May 31: June 15
    June 1 – August 31: September 15
    September 1 – December 31: January 15* of the following year. *See January payment in Chapter 2 of Publication 505, Tax Withholding and Estimated Tax

Save Docs to TaxPayments in Dropbox.

 - [ ] Look at Profits and Losses
 - [ ] Estimate the amount of taxes that need to be owed.
 - [ ] Tell how much I should estimate
 - [ ] Pay the taxes
 - [ ] If Q1 also pay $800 California LLC Tax
 - [ ] If Q1 Pay Statement of Information on Even Years (2018, 2020, 2022)

### Business Permit / Santa Rosa

Go to the santarosa.bizlicenseonline.com and fill it out on June 29th of every year.

### Review Budget

https://docs.google.com/spreadsheets/d/1lbi67AeJclaoLr1my-dq4_X9gPY4eJ9pvq2Wt24lyp0/edit#gid=661856552

### Review Vendors

 - [ ] Go through vendors
 - [ ] Figure out if we can use alternates
