### ISSUE TITLE
2018-09-26T21:22:49Z: Daily Todo

### ISSUE THREAD

**Issue by abhiyerra** [startupsonoma/community#14]
# Daily

## Sales / Pipedrive

 - [ ] Contacted / Create Deal
 - [ ] Deals / Lead In
    - https://startupsonomacounty.pipedrive.com/pipeline/1/user/everyone
    - Create Activities (What the Next Steps Are)
    - Find Contact Information / Research Contact Information
 - [ ] People/ Ensure Emails Exist
    - All these People Need to Have Emails associated with them:
        - https://startupsonomacounty.pipedrive.com/persons/list
    - Note: Ask Dana, Tyler or Abhi for information

## Trello

https://trello.com/b/JzOSb2w9/tasks

 - [ ] Organize
 - [ ] Admin Tasks

# Building

## Cleaning Walkthrough

Write the following of anything that is dirty. Make notes of this in Trello
so we can get through them.

- [ ] Trim
- [ ] Food Levels
- [ ] Table Tops
- [ ] Papers
- [ ] Floor
- [ ] Conference Room 1
- [ ] Conference Room 2
- [ ] Whiteboards
- [ ] Walls
- [ ] Lights
- [ ] Printers
- [ ] Side
    - [ ] Plants growing
    - [ ] Unclean
